import KeyboardKey from './key';
import KeyboardRow from './keyboardRow';

export const keyboardEnglisLayout = [
  new KeyboardRow([
    new KeyboardKey('Backquote', '`', '~'),
    new KeyboardKey('Digit1', '1', '!'),
    new KeyboardKey('Digit2', '2', '@'),
    new KeyboardKey('Digit3', '3', '#'),
    new KeyboardKey('Digit4', '4', '$'),
    new KeyboardKey('Digit5', '5', '%'),
    new KeyboardKey('Digit6', '6', '^'),
    new KeyboardKey('Digit7', '7', '&'),
    new KeyboardKey('Digit8', '8', '*'),
    new KeyboardKey('Digit9', '9', '('),
    new KeyboardKey('Digit0', '0', ')'),
    new KeyboardKey('Minus', '-', '_'),
    new KeyboardKey('Equal', '=', '+'),
    new KeyboardKey('Backspace', 'Backspace'),
  ]),
  new KeyboardRow([
    new KeyboardKey('Tab', 'Tab'),
    new KeyboardKey('KeyQ', 'q', 'Q'),
    new KeyboardKey('KeyW', 'w', 'W'),
    new KeyboardKey('KeyE', 'e', 'E'),
    new KeyboardKey('KeyR', 'r', 'R'),
    new KeyboardKey('KeyT', 't', 'T'),
    new KeyboardKey('KeyY', 'y', 'Y'),
    new KeyboardKey('KeyU', 'u', 'U'),
    new KeyboardKey('KeyI', 'i', 'I'),
    new KeyboardKey('KeyO', 'o', 'O'),
    new KeyboardKey('KeyP', 'p', 'P'),
    new KeyboardKey('BracketLeft', '[', '{'),
    new KeyboardKey('BracketRight', ']', '}'),
    new KeyboardKey('Backslash', '\\', '|'),
    new KeyboardKey('Delete', 'Del'),
  ]),
  new KeyboardRow([
    new KeyboardKey('CapsLock', 'CapsLk'),
    new KeyboardKey('KeyA', 'a', 'A'),
    new KeyboardKey('KeyS', 's', 'S'),
    new KeyboardKey('KeyD', 'd', 'D'),
    new KeyboardKey('KeyF', 'f', 'F'),
    new KeyboardKey('KeyG', 'g', 'G'),
    new KeyboardKey('KeyH', 'h', 'H'),
    new KeyboardKey('KeyJ', 'j', 'J'),
    new KeyboardKey('KeyK', 'k', 'K'),
    new KeyboardKey('KeyL', 'l', 'L'),
    new KeyboardKey('Semicolon', ';', ':'),
    new KeyboardKey('Quote', '\'', '"'),
    new KeyboardKey('Enter', 'Enter'),
  ]),
  new KeyboardRow([
    new KeyboardKey('ShiftLeft', 'Shift'),
    new KeyboardKey('KeyZ', 'z', 'Z'),
    new KeyboardKey('KeyX', 'x', 'X'),
    new KeyboardKey('KeyC', 'c', 'C'),
    new KeyboardKey('KeyV', 'v', 'V'),
    new KeyboardKey('KeyB', 'b', 'B'),
    new KeyboardKey('KeyN', 'n', 'N'),
    new KeyboardKey('KeyM', 'm', 'M'),
    new KeyboardKey('Comma', ',', '<'),
    new KeyboardKey('Period', '.', '>'),
    new KeyboardKey('Slash', '/', '?'),
    new KeyboardKey('ArrowUp', '↑'),
    new KeyboardKey('ShiftRight', 'Shift'),
  ]),
  new KeyboardRow([
    new KeyboardKey('ControlLeft', 'Ctrl'),
    new KeyboardKey('MetaLeft', 'Win'),
    new KeyboardKey('AltLeft', 'Alt'),
    new KeyboardKey('Space', ''),
    new KeyboardKey('AltRight', 'Alt'),
    new KeyboardKey('ArrowLeft', '←'),
    new KeyboardKey('ArrowDown', '↓'),
    new KeyboardKey('ArrowRight', '→'),
    new KeyboardKey('ControlRight', 'Ctrl'),
  ]),
];

export const keyboardRussianLayout = [
  new KeyboardRow([
    new KeyboardKey('Backquote', '`', '~'),
    new KeyboardKey('Digit1', '1', '!'),
    new KeyboardKey('Digit2', '2', '@'),
    new KeyboardKey('Digit3', '3', '#'),
    new KeyboardKey('Digit4', '4', '$'),
    new KeyboardKey('Digit5', '5', '%'),
    new KeyboardKey('Digit6', '6', '^'),
    new KeyboardKey('Digit7', '7', '&'),
    new KeyboardKey('Digit8', '8', '*'),
    new KeyboardKey('Digit9', '9', '('),
    new KeyboardKey('Digit0', '0', ')'),
    new KeyboardKey('Minus', '-', '_'),
    new KeyboardKey('Equal', '=', '+'),
    new KeyboardKey('Backspace', 'Backspace'),
  ]),
  new KeyboardRow([
    new KeyboardKey('Tab', 'Tab'),
    new KeyboardKey('KeyQ', 'q', 'Q'),
    new KeyboardKey('KeyW', 'w', 'W'),
    new KeyboardKey('KeyE', 'e', 'E'),
    new KeyboardKey('KeyR', 'r', 'R'),
    new KeyboardKey('KeyT', 't', 'T'),
    new KeyboardKey('KeyY', 'y', 'Y'),
    new KeyboardKey('KeyU', 'u', 'U'),
    new KeyboardKey('KeyI', 'i', 'I'),
    new KeyboardKey('KeyO', 'o', 'O'),
    new KeyboardKey('KeyP', 'p', 'P'),
    new KeyboardKey('BracketLeft', '[', '{'),
    new KeyboardKey('BracketRight', ']', '}'),
    new KeyboardKey('Backslash', '\\', '|'),
    new KeyboardKey('Key', 'q', 'Q'),
    new KeyboardKey('Delete', 'Del'),
  ]),
  new KeyboardRow([
    new KeyboardKey('CapsLock', 'CapsLk'),
    new KeyboardKey('KeyA', 'a', 'A'),
    new KeyboardKey('KeyS', 's', 'S'),
    new KeyboardKey('KeyD', 'd', 'D'),
    new KeyboardKey('KeyF', 'f', 'F'),
    new KeyboardKey('KeyG', 'g', 'G'),
    new KeyboardKey('KeyH', 'h', 'H'),
    new KeyboardKey('KeyJ', 'j', 'J'),
    new KeyboardKey('KeyK', 'k', 'K'),
    new KeyboardKey('KeyL', 'l', 'L'),
    new KeyboardKey('Semicolon', ';', ':'),
    new KeyboardKey('Quote', '\'', '"'),
    new KeyboardKey('Enter', 'Enter'),
  ]),
  new KeyboardRow([
    new KeyboardKey('ShiftLeft', 'Shift'),
    new KeyboardKey('KeyZ', 'z', 'Z'),
    new KeyboardKey('KeyX', 'x', 'X'),
    new KeyboardKey('KeyC', 'c', 'C'),
    new KeyboardKey('KeyV', 'v', 'V'),
    new KeyboardKey('KeyB', 'b', 'B'),
    new KeyboardKey('KeyN', 'n', 'N'),
    new KeyboardKey('KeyM', 'm', 'M'),
    new KeyboardKey('Comma', ',', '<'),
    new KeyboardKey('Period', '.', '>'),
    new KeyboardKey('Slash', '/', '?'),
    new KeyboardKey('ArrowUp', '↑'),
    new KeyboardKey('ShiftRight', 'Shift'),
  ]),
  new KeyboardRow([
    new KeyboardKey('ControlLeft', 'Ctrl'),
    new KeyboardKey('MetaLeft', 'Win'),
    new KeyboardKey('AltLeft', 'Alt'),
    new KeyboardKey('Space', 'Space'),
    new KeyboardKey('AltRight', 'Alt'),
    new KeyboardKey('ArrowLeft', '←'),
    new KeyboardKey('ArrowDown', '↓'),
    new KeyboardKey('ArrowRight', '→'),
    new KeyboardKey('ControlRight', 'Ctrl'),
  ]),
];
